name: Code Checks

permissions:
  contents: read

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  validate:
    name: Validate Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            ~/.cache/pip
          key: uv-cache-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            uv-cache-

      - name: Set up Python environment
        run: |
          wget -qO- https://astral.sh/uv/install.sh | sh
          uv sync --group dev

      - name: Run Ruff (PEP 8 Formatting)
        run: uv run make format

      - name: Run Ruff (Linting + Docstrings)
        run: uv run make check

      - name: Run vulture (Duplicate Code)
        run: uv run make vulture

      - name: Run xenon (Cyclomatic Complexity)
        run: uv run make xenon

      - name: Run bandit (Security)
        run: uv run make bandit

      - name: Run pyright (Type Checking)
        run: uv run make pyright

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: validate

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            ~/.cache/pip
          key: uv-cache-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            uv-cache-

      - name: Set up Python environment
        run: |
          wget -qO- https://astral.sh/uv/install.sh | sh
          uv sync --group dev

      - name: Run tests
        run: uv run pytest --maxfail=1 --disable-warnings -v -s
        env:
          AMAZONCAPTCHA_DEBUG_PATH: /tmp/amazoncaptcha_debug.log

      - name: Upload debug artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: amazoncaptcha-debug
          path: /tmp/amazoncaptcha_debug.log
