name: Python Code Checks

permissions:
  contents: read

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  test:
    name: Validate Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Primes
        id: cache-primes
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            ~/.cache/pip
          key: uv-cache-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            uv-cache-

      - name: Set up Python environment
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install uv

      - name: Install dependencies
        run: |
          source .venv/bin/activate
          uv pip install -r <(uv pip compile --all-extras pyproject.toml)
          uv pip install ruff tox xenon bandit pyright vulture

      - name: Run Ruff (PEP 8 Formatting)
        run: |
          source .venv/bin/activate
          make format

      - name: Run Ruff (Linting + Docstrings)
        run: |
          source .venv/bin/activate
          make check

      - name: Run vulture (Duplicate Code)
        run: |
          source .venv/bin/activate
          make vulture

      - name: Run xenon (Cyclomatic Complexity)
        run: |
          source .venv/bin/activate
          make xenon

      - name: Run bandit (Security)
        run: |
          source .venv/bin/activate
          make bandit

      - name: Run pyright (Type Checking)
        run: |
          source .venv/bin/activate
          make pyright
