name: CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache Primes
        id: cache-primes
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            ~/.cache/pip
          key: uv-cache-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            uv-cache-

      - name: Set up Python environment
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install uv

      - name: Install dependencies
        run: |
          source .venv/bin/activate
          uv pip install -r <(uv pip compile --all-extras pyproject.toml)
          uv pip install ruff tox xenon bandit pyright vulture pytest

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest --maxfail=1 --disable-warnings -v
